### ISSUE TITLE
Forgot to change ski.js size

### ISSUE THREAD

**Issue by 99TheDark** [thelegendski/ski.js#18]
This is very minor, but you say the min takes up 10.7kb, but it takes 11.9kb.

**Comment by thelegendski** [comment]
the size will be changed once all final revisions have been made, :). currently, i still need to create a responsive canvas an' test for any bugs.

**Comment by 99TheDark** [comment]
That was tricky, I spent hours figuring that out at the beginning. See my size function for reference, then it become pretty easy. Also might want to comment this issue as resolved.

**Comment by thelegendski** [comment]
done, :). i'll go take a look, ;p.
