### ISSUE TITLE
All shaders are opaque

### ISSUE THREAD

**Issue by 99TheDark** [thelegendski/ski.js#19]
You forgot to add tex.a to all filters. This also makes the opaque filter completely useless. It can be nice to have transparent canvases or elements if you intend to add filters to images.

**Comment by 99TheDark** [comment]
Also, I'm not sure if this is on purpose or not, but your posterize filter has /256.0 which doesn't make much sense for the range 0-255. If you change it to 255, you can cancel the *255 and /255 which would also speed stuff up slightly.

**Comment by thelegendski** [comment]
done!

fixed!

all floats are now `lowp`, ;p.

[here's](https://www.khanacademy.org/cs/-/5116098904637440) a reference to where my code is for now. i'll port it over here in the next release.
