### ISSUE TITLE
ski.js flaws

### ISSUE THREAD

**Issue by SMVthe1st** [thelegendski/ski.js#23]
> @SMVthe1st
can you make a list of all requests for features/bugz for ski.js as well as any additional but not essential tasks that have been asked of me?

[Here](https://www.khanacademy.org/computer-programming/skijs-flaws/4727953536892928) we go.
I think this is all I have atm, might look into more if you need me to =)

**Comment by thelegendski** [comment]
done! check v1.1.0.
